version: '3'

services:
  mariadb:
    image: mariadb:10
    container_name: '${PROJECT_NAME}_mariadb'
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - ./db:/var/lib/mysql # Use bind mount

  app:
    image: strathos/php-nginx-supervisord:latest
    container_name: '${PROJECT_NAME}_app'
    depends_on:
      - mariadb
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PUID: $PUID
      PGID: $PGID
      SITE_URL: $PROJECT_BASE_URL
      CIRCLECI_API_KEY: $CIRCLECI_API_KEY
      SITE_HASH_SALT: $SITE_HASH_SALT
    volumes:
      - ./src:/var/www/html
    labels:
      - 'traefik.backend=${PROJECT_NAME}_app'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: '${PROJECT_NAME}_mailhog'
    labels:
      - 'traefik.backend=${PROJECT_NAME}_mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

  #  drupal-node:
  #    image: wodby/drupal-node:$DRUPAL_NODE_TAG
  #    container_name: "${PROJECT_NAME}_drupal_nodejs"
  #    environment:
  #       NODE_SERVICE_KEY: node-service-key
  #    labels:
  #      - 'traefik.backend=${PROJECT_NAME}_nodejs'
  #      - 'traefik.port=8080'
  #      - 'traefik.frontend.rule=Host:nodejs.${PROJECT_BASE_URL}'
  #    volumes:
  #      - ./path/to/your/single-page-app:/app
  #    command: sh -c 'npm install && npm run start'

  traefik:
    image: traefik:maroilles
    container_name: '${PROJECT_NAME}_traefik'
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '${PROJECT_PORT}:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
